/*
------------------------------------------------
Generated by Cradle 2.0.2.0
https://github.com/daterre/Cradle

Original file: these.html
Story format: Harlowe
------------------------------------------------
*/

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Cradle;
using IStoryThread = System.Collections.Generic.IEnumerable<Cradle.StoryOutput>;
using Cradle.StoryFormats.Harlowe;

public partial class @these: Cradle.StoryFormats.Harlowe.HarloweStory
{
	#region Variables
	// ---------------

	public class VarDefs: RuntimeVars
	{
		public VarDefs()
		{
			VarDef("boolean", () => this.@boolean, val => this.@boolean = val);
		}

		public StoryVar @boolean;
	}

	public new VarDefs Vars
	{
		get { return (VarDefs) base.Vars; }
	}

	// ---------------
	#endregion

	#region Initialization
	// ---------------

	public readonly Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros macros1;

	@these()
	{
		this.StartPassage = "intro";

		base.Vars = new VarDefs() { Story = this, StrictMode = true };

		macros1 = new Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros() { Story = this };

		base.Init();
		passage1_Init();
		passage2_Init();
		passage3_Init();
		passage4_Init();
	}

	// ---------------
	#endregion

	// .............
	// #1: intro

	void passage1_Init()
	{
		this.Passages[@"intro"] = new StoryPassage(@"intro", new string[]{ "VOID-Speaking", }, passage1_Main);
	}

	IStoryThread passage1_Main()
	{
		Vars.boolean = true;
		yield return lineBreak();
		yield return lineBreak();
		if(Vars.boolean) {
		yield return link("you see this ", " thisone", null);
		}
		yield return lineBreak();
		yield return lineBreak();
		yield return text("done");
		yield return lineBreak();
		yield return lineBreak();
		yield break;
	}


	// .............
	// #2:  willing to give

	void passage2_Init()
	{
		this.Passages[@" willing to give"] = new StoryPassage(@" willing to give", new string[]{  }, passage2_Main);
	}

	IStoryThread passage2_Main()
	{
		yield return text("Double-click this passage to edit it.");
		yield break;
	}


	// .............
	// #3:  refuse

	void passage3_Init()
	{
		this.Passages[@" refuse"] = new StoryPassage(@" refuse", new string[]{  }, passage3_Main);
	}

	IStoryThread passage3_Main()
	{
		yield return text("Double-click this passage to edit it.");
		yield break;
	}


	// .............
	// #4:  thisone

	void passage4_Init()
	{
		this.Passages[@" thisone"] = new StoryPassage(@" thisone", new string[]{  }, passage4_Main);
	}

	IStoryThread passage4_Main()
	{
		yield return text("Double-click this passage to edit it.");
		yield break;
	}


}